from typing import Protocol


class ModelServingClient(Protocol):
    async def predict(self, image_bytes: bytes) -> dict: ...
    async def get_model_registry(self) -> dict: ...


class ReasoningServiceClient(Protocol):
    async def symptom_match(self, observations: dict) -> list[str]: ...
    async def qa_knowledge(self, diseases: list[str]) -> dict: ...
    async def fuse(self, ensemble_belief: dict, symptom_evidence: dict, qa_evidence: list[dict]) -> dict: ...
    async def get_remedies(self, disease: str) -> dict: ...


class LLMAdapter(Protocol):
    async def extract_observations(self, description: str) -> dict: ...
    async def generate_explanation(self, diagnosis: dict, recommendations: dict) -> str: ...
    async def answer_followup(self, session_context: dict, question: str) -> str: ...
